api0:
    build: .
    dockerfile: docker-api-v1.0.dockerfile
    container_name: api0
    environment:
      - ASPNET_ENV=Development
      
api1:
    build: .
    dockerfile: docker-api-v1.0.dockerfile
    container_name: api1
    environment:
      - ASPNET_ENV=Development
      
api2:
    build: .
    dockerfile: docker-api-v1.0.dockerfile
    container_name: api2
    environment:
      - ASPNET_ENV=Development
      
api3:
    build: .
    dockerfile: docker-api-v1.1.dockerfile
    container_name: api3
    environment:
      - ASPNET_ENV=Development
      
api4:
    build: .
    dockerfile: docker-api-v1.1.dockerfile
    container_name: api4
    environment:
      - ASPNET_ENV=Development
      
api5:
    build: .
    dockerfile: docker-api-v1.1.dockerfile
    container_name: api5
    environment:
      - ASPNET_ENV=Development
      
api-lb:
    build: .
    dockerfile: docker-haproxy.dockerfile
    container_name: api-lb
    volumes:
      - ./haproxy-data:/apps/haproxy
    ports:
      - "5000:80"
    links:
      - api0
      - api1
      - api2
      - api3
      - api4
      - api5